### ISSUE TITLE
[Package Request] JetBrains

### ISSUE THREAD

**Issue by CoolPlayLin** [CoolPlayLin/AutoPublish#10]
# Overview
All software from JetBrains
- https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains

**Comment by vedantmgoyal9** [comment]
@CoolPlayLin hello, please check messages at Gitter (app.gitter.im)

**Comment by CoolPlayLin** [comment]
@vedantmgoyal9 Sorry, I don't know why I can not join it
![image](https://github.com/CoolPlayLin/AutoPublish/assets/96709586/8398b7f8-d2b5-4c35-b356-ca1d8514e35e)

**Comment by CoolPlayLin** [comment]
Jetbrains has been already included in other automations

**Comment by CoolPlayLin** [comment]
@vedantmgoyal9 
![image](https://github.com/CoolPlayLin/AutoPublish/assets/96709586/32a67e88-b887-4291-90c7-26984274fd09)
